import { defineConfig } from "oxlint";
import core from "ultracite/oxlint/core";
import next from "ultracite/oxlint/next";
import react from "ultracite/oxlint/react";
export default defineConfig({
  extends: [core, react, next],
  rules: {
    complexity: "allow",
    eqeqeq: "allow",
    "func-style": "allow",
    "no-empty-function": "allow",
    "no-eq-null": "allow",
    "no-loop-func": "allow",
    "no-param-reassign": "allow",
    "no-plusplus": "allow",
    "no-promise-executor-return": "allow",
    "no-shadow": "allow",
    "no-use-before-define": "allow",
    "no-useless-return": "allow",
    "prefer-destructuring": "allow",
    "require-unicode-regexp": "allow",
    "sort-keys": "allow",
    "import/first": "allow",
    "import/no-duplicates": "allow",
    "import/no-named-as-default-member": "allow",
    "promise/avoid-new": "allow",
    "promise/prefer-await-to-callbacks": "allow",
    "promise/prefer-await-to-then": "allow",
    "typescript/no-explicit-any": "allow",
    "typescript/no-non-null-assertion": "allow",
    "unicorn/consistent-function-scoping": "allow",
    "unicorn/filename-case": "allow",
    "unicorn/no-abusive-eslint-disable": "allow",
    "unicorn/no-array-for-each": "allow",
    "unicorn/no-await-expression-member": "allow",
    "unicorn/no-immediate-mutation": "allow",
    "unicorn/no-useless-length-check": "allow",
    "unicorn/no-useless-undefined": "allow",
    "unicorn/prefer-spread": "allow",
    "unicorn/prefer-ternary": "allow",
    "vitest/max-expects": "allow",
    "vitest/no-conditional-expect": "allow",
    "vitest/require-mock-type-parameters": "allow",
    "vitest/require-to-throw-message": "allow",
    "vitest/require-top-level-describe": "allow",
  },
  overrides: [
    {
      files: ["**/*.{test,spec}.{ts,tsx,js,jsx}"],
      rules: {
        "vitest/max-expects": "allow",
        "vitest/no-conditional-expect": "allow",
        "vitest/require-mock-type-parameters": "allow",
        "vitest/require-to-throw-message": "allow",
        "vitest/require-top-level-describe": "allow",
      },
    },
  ],
});
