import { defineConfig } from "oxlint";

// Oxlint defaults (correctness category; typescript/unicorn/oxc plugins on) plus
// type-aware linting via oxlint-tsgolint, strict TypeScript escape-hatch rules,
// and React Compiler-derived rules from the react plugin.
export default defineConfig({
  plugins: ["unicorn", "typescript", "oxc", "react", "vitest"],
  options: {
    typeAware: true,
  },
  rules: {
    "typescript/ban-ts-comment": "error",
    "typescript/consistent-type-assertions": ["error", { assertionStyle: "never" }],
    "typescript/no-explicit-any": "error",
    "typescript/no-non-null-assertion": "error",
    "typescript/no-unsafe-argument": "error",
    "typescript/no-unsafe-assignment": "error",
    "typescript/no-unsafe-call": "error",
    "typescript/no-unsafe-member-access": "error",
    "typescript/no-unsafe-return": "error",
    "typescript/no-unsafe-type-assertion": "error",
    "typescript/no-unnecessary-type-assertion": "error",
    // React Compiler correctness (recommended preset)
    "react/error-boundaries": "error",
    "react/globals": "error",
    "react/immutability": "error",
    "react/incompatible-library": "error",
    "react/preserve-manual-memoization": "error",
    "react/purity": "error",
    "react/refs": "error",
    "react/set-state-in-effect": "error",
    "react/set-state-in-render": "error",
    "react/static-components": "error",
    "react/use-memo": "error",
    "react/void-use-memo": "error",
    // React Compiler restriction
    "react/unsupported-syntax": "error",
    "react/invariant": "error",
    "react/rule-suppression": "error",
    "react/syntax": "error",
    "react/todo": "error",
    // React Compiler perf
    "react/no-deriving-state-in-effects": "error",
    // React Compiler suspicious
    "react/capitalized-calls": "error",
    "react/exhaustive-effect-dependencies": "error",
    "react/hooks": "error",
    "react/memo-dependencies": "error",
    // Vitest correctness & hygiene (0 existing violations)
    "vitest/no-conditional-tests": "error",
    "vitest/no-focused-tests": "error",
    "vitest/no-disabled-tests": "error",
    "vitest/no-standalone-expect": "error",
    "vitest/valid-describe-callback": "error",
    "vitest/valid-expect": "error",
    "vitest/valid-expect-in-promise": "error",
    "vitest/no-identical-title": "error",
    "vitest/no-test-prefixes": "error",
    "vitest/no-test-return-statement": "error",
    "vitest/no-import-node-test": "error",
    "vitest/no-commented-out-tests": "error",
    "vitest/require-awaited-expect-poll": "error",
    "vitest/hoisted-apis-on-top": "error",
    "vitest/prefer-to-have-length": "error",
    "vitest/prefer-to-contain": "error",
    "vitest/prefer-to-be": "error",
    "vitest/prefer-comparison-matcher": "error",
    "vitest/prefer-called-once": "error",
    "vitest/prefer-strict-equal": "error",
    // Temporarily disabled while fixing offenders in subsequent commits
    "vitest/valid-title": "off",
    "vitest/require-mock-type-parameters": "off",
    "vitest/no-conditional-expect": "off",
    "vitest/require-to-throw-message": "off",
  },
});
